---
  - src: git@github.com:AlexeySetevoi/ansible-clickhouse.git
    scm: git
    version: "1.13"
    name: clickhouse 

  - src: git@github.com:decimal-kmn/vector-role.git
    scm: git
    version: "1.0"
    name: vector 

  - src: git@github.com:decimal-kmn/lighthouse-role.git
    scm: git
    version: "1.0"
    name: lighthouse